const consts = {

EMPTY: "EMPTY",
SHOW: "SHOW",
CREATE: "CREATE",
SAVING: "SAVING",
DELETING: "DELETING",
CONFIRM: "CONFIRM",
EDIT: "EDIT",
ERROR_SAVE: "ERROR_SAVE",
ERROR_DELETE: "ERROR_DELETE",

}

export default consts;